title: OpenRouter AI Usage Analysis
author: Development Data Partnership
logo: docs/images/logo.png
only_build_toc_files: false

execute:
  execute_notebooks: off

repository:
  url: https://github.com/towera/open-router-analysis
  branch: main

html:
  home_page_in_navbar: false
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://towera.github.io/open-router-analysis
  extra_footer: |
    <div>
      Country borders or names do not necessarily reflect the World Bank Group's official position...
    </div>
  favicon: docs/images/favicon.ico

bibtex_bibfiles:
  - docs/bibliography.bib

sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"